---
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
spec:
  type: ClusterIP
  ports:
    - port: 16379
      targetPort: 16379
#      name: client
#    - port: 6379
#      targetPort: 6379
#      name: gossip
  selector:
    app: redis-cluster