apiVersion: v1
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: redis-standalone
    name: redis-standalone
  spec:
    serviceName: redis-standalone
    replicas: 1
    selector:
      app: redis-standalone
    template:
      metadata:
        labels:
          app: redis-standalone
      spec:
        containers:
        - image: redis:5.0.1-alpine
          imagePullPolicy: Always
          name: redis-standalone
          volumeMounts:
            - mountPath: /redis-data
              name: data 
          ports:
            - containerPort: 6379
          resources: {}
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
          - name: data
            persistentVolumeClaim:
                claimName: data-redis-standalone-0
    test: false
  status: {}
kind: List
metadata: {}
